services:

  mysql:
    image: mysql:8.4
    container_name: mysql_proyecto
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: proyectodb
      MYSQL_USER: proyecto
      MYSQL_PASSWORD: proyecto123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  ventas-service:
    image: ventas-service:latest
    container_name: ventas_service

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: proyectodb
      DB_USERNAME: proyecto
      DB_PASSWORD: proyecto123

    restart: on-failure

  despachos-service:
    image: despachos-service:latest
    container_name: despachos_service

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8081:8081"

    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: proyectodb
      DB_USERNAME: proyecto
      DB_PASSWORD: proyecto123

    restart: on-failure

volumes:
  mysql_data: