apiVersion: v1
kind: Service
metadata:
  name: despachos-service
  namespace: proyecto
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  type: LoadBalancer

  selector:
    app: despachos-service

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081