apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: proyecto

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: 934438538002.dkr.ecr.us-east-1.amazonaws.com/frontend-despacho:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 80