apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: proyecto
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: proyectodb
  MYSQL_USER: proyecto
  MYSQL_PASSWORD: proyecto123